- name: Refresh Kernel
  command: sysctl -e -p
  sudo: True

- name: Restart Networking
  command: service network restart
  sudo: True

- name: Restart Node
  command: shutdown -r now "Ansible updated triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait For Node
  local_action: 
    module: wait_for
      host={{ ansible_ssh_host }} 
      port=22
      delay=1
      timeout=300
  sudo: False
