# -*- mode: ruby -*-
# vi: set ft=ruby :

require('yaml')

# Define globals.
$configuration = YAML.load_file("cluster.yml")

def generateStaticConfiguration(global_config)
  global_config.vm.box = "#{$configuration['cluster']['box']}"
  global_config.ssh.pty = true
  global_config.landrush.tld = "#{$configuration['cluster']['domain']}"
  global_config.landrush.enabled = true
  global_config.vm.synced_folder '.', '/vagrant', disabled: true
  global_config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/main.yml"
    ansible.limit = "all"
  end
end

def generateCommonNodeConfiguration(global_config, node, node_spec)
  global_config.vm.define node["name"] do |node_config|
    node_config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = node_spec["memory"]
      vb.cpus = node_spec["cpu"]
      vb.customize ['storagectl', :id, '--name', 'SATA Controller', '--portcount', 30]
      node_spec["storage"].each.with_index do |hdd_config, index|
        disk = "#{hdd_config['host_dir']}/vb_disk_#{node['name']}_#{index}.vdi"
        unless File.exist?(disk)
          vb.customize ['createhd', '--filename', disk, '--size', hdd_config["capacity"]]
        end
        vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', (1 + index), '--device', 0, '--type', 'hdd', '--medium', disk]
      end
    end
    node_config.vm.hostname = "#{node['name']}.#{$configuration['cluster']['domain']}"
    node_config.vm.network "private_network", ip: node["ip"]
  end
end

Vagrant.configure(2) do |global_config|
  # Set global configuration.
  generateStaticConfiguration(global_config)

  # Build all node configuration.
  ["masters", "workers"].each do |node_type|
    node_spec = $configuration["cluster"][node_type]
    $configuration["cluster"][node_type]["nodes"].each do |node|
      generateCommonNodeConfiguration(global_config, node, node_spec)
    end
  end

end
