# -*- mode: ruby -*-
# vi: set ft=ruby :

require('yaml')

cluster = YAML.load_file("cluster.yml")
node_count = cluster["configuration"]["masters"]["count"] + cluster["configuration"]["workers"]["count"]

Vagrant.configure(2) do |config|
  # Set common node options.
  config.vm.box = "#{cluster['configuration']['box']}"
  config.ssh.pty = true
  config.landrush.tld = "#{cluster['configuration']['domain']}"
  config.landrush.enabled = true
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/main.yml"
    ansible.limit = "all"
  end

  # Build out each node.
  node_count.times do |i|
    node_id = "node#{i}"
    config.vm.define node_id do |node|
      node.vm.provider "virtualbox" do |vb|
        disk = "/tmp/vb_disk_node#{i}.vdi"
        vb.gui = false
        vb.memory = 2048
        vb.cpus = 2
        unless File.exist?(disk)
          vb.customize ['createhd', '--filename', disk, '--size', 10 * 1024]
        end
        vb.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', disk]
      end
      node.vm.hostname = "#{node_id}.#{cluster['configuration']['domain']}"
      node.vm.network "private_network", ip: "192.168.25.#{100 + i}"
      if i == 0 then
        node.vm.network "forwarded_port", guest: 7180, host: 7180
      end
    end
  end

end
